"use client";

import React from "react";
import Link from "next/link";
import { officialLinks } from "@/config/official-links";
import { formatTimestamp } from "@/lib/timestamps";
import { AlertIcon, ArrowIcon, CloudIcon, ExternalIcon, PinIcon, ShieldIcon } from "@/components/icons";
import { usePreferences } from "@/components/preferences";
import { localizeForecastDescription } from "@/lib/forecast-labels";
import type { AreaSummary } from "@/types";

const availabilityMs: Record<string,string> = {
  "Weather warnings are temporarily unavailable.": "Amaran cuaca tidak tersedia buat sementara waktu.",
  "A forecast for this location is temporarily unavailable.": "Ramalan untuk lokasi ini tidak tersedia buat sementara waktu.",
  "Current official JKM listings found nearby. Confirm status before travelling.": "Senarai rasmi JKM semasa ditemukan berdekatan. Sahkan status sebelum bergerak.",
  "Live JKM evacuation-centre data is temporarily unavailable.": "Data langsung PPS JKM tidak tersedia buat sementara waktu.",
  "The current official JKM feed lists no active evacuation centres within 15 km of this location.": "Suapan rasmi JKM semasa tidak menyenaraikan PPS aktif dalam lingkungan 15 km dari lokasi ini.",
};

export function AreaContent({summary,demo}:{summary:AreaSummary;demo:boolean}) {
  const { language } = usePreferences();
  const ms = language === "ms";
  const c = (en:string,bm:string) => ms ? bm : en;
  const locale = ms ? "ms-MY" : "en-MY";
  const timestamp = (value?:string) => value ? formatTimestamp(value, locale) : c("Timestamp unavailable","Masa tidak tersedia");
  const message = (value?:string) => value && ms ? availabilityMs[value] ?? value : value;
  const statusLabels = ms ? { active:"Aktif sekarang", historical:"Pernah digunakan sebagai PPS", inactive:"Disahkan tidak aktif", unknown:"Status operasi semasa tidak diketahui" } : { active:"Active now", historical:"Previously used as an evacuation centre", inactive:"Confirmed inactive", unknown:"Current operating status unknown" };
  const warningTitle = (title:string,titleMs?:string) => ms ? titleMs ?? "Amaran cuaca rasmi" : title;
  const warningDescription = (description:string,descriptionMs?:string) => ms ? descriptionMs ?? "Lihat sumber rasmi untuk butiran amaran." : description;
  return <main id="main" className="area-page">
    {demo && <div className="demo-banner"><AlertIcon/><strong>{c("Demonstration scenario — not a current warning","Senario demonstrasi — bukan amaran semasa")}</strong><span>{c("Historical/mock fixture dated 18 December 2021","Data sejarah/simulasi bertarikh 18 Disember 2021")}</span></div>}
    <section className="area-hero"><div className="container"><div className="breadcrumbs"><Link href="/">{c("Home","Utama")}</Link><span>/</span><span>{c("Area check","Semakan kawasan")}</span></div><div className="area-title-row"><div><span className="eyebrow"><PinIcon/> {summary.mode === "live" ? c("Selected location","Lokasi dipilih") : c("Demonstration location","Lokasi demonstrasi")}</span><h1>{summary.location.name}</h1><p>{[summary.location.district,summary.location.state].filter(Boolean).join(", ")}</p></div></div></div></section>
    <div className="container area-layout"><aside className="area-aside"><nav aria-label={c("Page sections","Bahagian halaman")}><span>{c("On this page","Dalam halaman ini")}</span><a href="#warnings">{c("Weather warnings","Amaran cuaca")}</a><a href="#forecast">{c("Weather forecast","Ramalan cuaca")}</a><a href="#nearby-help">{c("Nearby help","Bantuan berdekatan")}</a><a href="#resources">{c("Official resources","Sumber rasmi")}</a></nav></aside>
      <div className="area-content">
        <section id="warnings" className="result-section"><div className="result-heading"><span className="step-number">01</span><div><h2>{c("Current weather warnings","Amaran cuaca semasa")}</h2><p>{c("Official warnings that match the selected area.","Amaran rasmi yang meliputi kawasan dipilih.")}</p></div></div>
          {summary.weatherWarnings.length ? <div className="warning-list">{summary.weatherWarnings.map((warning) => <article className="warning-detail" key={warning.id}><div><AlertIcon/><span>{summary.mode === "demonstration" ? c("Demonstration warning","Amaran demonstrasi") : c("Official warning","Amaran rasmi")}</span></div><h3>{warningTitle(warning.title,warning.titleMs)}</h3><p>{warningDescription(warning.description,warning.descriptionMs)}</p><dl><div><dt>{c("Issued","Dikeluarkan")}</dt><dd>{timestamp(warning.issuedAt)}</dd></div><div><dt>{c("Valid until","Sah sehingga")}</dt><dd>{timestamp(warning.validUntil)}</dd></div></dl><Link href="/data-sources">{summary.mode === "demonstration" ? c("Source: TolongNow demonstration fixture","Sumber: data demonstrasi TolongNow") : c("Source: MET Malaysia","Sumber: MET Malaysia")}</Link></article>)}</div> : <article className="indicator-card neutral"><span className="card-kicker">{c("Weather warnings","Amaran cuaca")}</span><div className="indicator-status"><AlertIcon/><strong>{summary.dataAvailability.warnings.available ? c("None found","Tiada amaran semasa") : c("Unavailable","Tidak tersedia")}</strong></div><p>{message(summary.dataAvailability.warnings.message) ?? c("No currently valid warning matched this area in the official feed.","Tiada amaran yang masih sah meliputi kawasan ini dalam suapan rasmi.")}</p><Link href="/data-sources">{c("Source: MET Malaysia","Sumber: MET Malaysia")} <ArrowIcon/></Link></article>}
        </section>
        <section id="forecast" className="result-section"><div className="result-heading"><span className="step-number">02</span><div><h2>{c("Weather forecast","Ramalan cuaca")}</h2><p>{c("Official district forecast from MET Malaysia.","Ramalan rasmi daerah daripada MET Malaysia.")}</p></div></div>{summary.forecast.length ? <div className="forecast-strip">{summary.forecast.slice(0,5).map((day)=><article key={day.date}><time dateTime={day.date}>{new Intl.DateTimeFormat(locale,{weekday:"short",day:"numeric",month:"short"}).format(new Date(`${day.date}T12:00:00+08:00`))}</time><CloudIcon/><strong>{localizeForecastDescription(day.description, language)}</strong><span>{day.minTemperature ?? "–"}° / {day.maxTemperature ?? "–"}°C</span></article>)}</div> : <div className="availability-box"><h3>{c("Forecast unavailable","Ramalan tidak tersedia")}</h3><p>{message(summary.dataAvailability.forecast.message)}</p></div>}<Link className="source-line" href="/data-sources">{c("Source: MET Malaysia via data.gov.my","Sumber: MET Malaysia melalui data.gov.my")} <ArrowIcon/></Link></section>
        <section id="nearby-help" className="result-section"><div className="result-heading"><span className="step-number">03</span><div><h2>{c("Nearby help","Bantuan berdekatan")}</h2><p>{c("Nearest active evacuation centres from official JKM data. Compare distance and occupancy, and follow local-authority directions before travelling.","Pusat pemindahan aktif terdekat berdasarkan data rasmi JKM. Bandingkan jarak dan jumlah penghuni, serta ikuti arahan pihak berkuasa tempatan sebelum bergerak.")}</p></div></div>
          {summary.nearbyPps.length ? <div className="pps-list">{summary.nearbyPps.map((pps) => <article className="pps-card" key={pps.id}><div className="pps-top"><span className={`status-pill ${pps.status}`}>{statusLabels[pps.status]}</span>{pps.distanceKm !== undefined && <span className="distance">{pps.distanceKm.toFixed(1)} km</span>}</div><h3>{pps.name}</h3><p>{pps.address}</p><a className="map-reference" href={`https://www.openstreetmap.org/?mlat=${pps.latitude}&mlon=${pps.longitude}#map=16/${pps.latitude}/${pps.longitude}`} target="_blank" rel="noreferrer">{c("View on OpenStreetMap","Lihat di OpenStreetMap")} <ExternalIcon/></a>{pps.status === "active" && <dl className="pps-stats"><div><dt>{c("People","Mangsa")}</dt><dd>{pps.victimCount?.toLocaleString(locale) ?? "–"}</dd></div><div><dt>{c("Families","Keluarga")}</dt><dd>{pps.familyCount?.toLocaleString(locale) ?? "–"}</dd></div><div><dt>{c("Capacity","Kapasiti")}</dt><dd>{pps.capacityPercent === undefined ? "–" : `${Math.round(pps.capacityPercent)}%`}</dd></div></dl>}<div className="verification"><ShieldIcon/><span>{pps.status === "active" ? c("Retrieved","Diperoleh") : c("Last verified","Kali terakhir disahkan")} {timestamp(pps.lastVerifiedAt)}</span></div></article>)}</div> : <div className="empty-state"><PeopleEmpty/><h3>{c("No active evacuation centres found nearby","Tiada PPS aktif ditemukan berdekatan")}</h3>{summary.dataAvailability.pps.message && <p>{message(summary.dataAvailability.pps.message)}</p>}</div>}
        </section>
        <section id="resources" className="result-section"><div className="result-heading"><span className="step-number">04</span><div><h2>{c("Official resources","Sumber rasmi")}</h2><p>{c("Check official services before travelling or acting on changing conditions.","Semak perkhidmatan rasmi sebelum bergerak atau mengambil tindakan apabila keadaan berubah.")}</p></div></div><div className="resource-list"><OfficialResource label={c("JKM active PPS service","Perkhidmatan PPS aktif JKM")} detail={c("Check active temporary evacuation centres","Semak Pusat Pemindahan Sementara yang aktif")} href={officialLinks.jkmPps}/><OfficialResource label="Public InfoBanjir" detail={c("Technical river information from JPS","Maklumat teknikal sungai daripada JPS")} href={officialLinks.jpsFlood}/><OfficialResource label={c("JKR disaster and road information","Maklumat bencana dan jalan raya JKR")} detail={c("Check official road notices","Semak notis rasmi jalan raya")} href={officialLinks.jkrRoads}/><OfficialResource label={c("NADMA disaster portal","Portal bencana NADMA")} detail={c("National official disaster information","Maklumat rasmi bencana negara")} href={officialLinks.nadma}/></div><div className="travel-warning"><AlertIcon/><p><strong>{c("Before travelling","Sebelum bergerak")}</strong><br/>{c("Standard map directions may not reflect current flooding or road closures. Check official road information before travelling.","Arah pada peta biasa mungkin tidak mencerminkan keadaan banjir atau penutupan jalan semasa. Semak maklumat rasmi jalan raya sebelum bergerak.")}</p></div></section>
        <section className="data-timestamp"><ShieldIcon/><div><strong>{c("Data checked","Data disemak")} {timestamp(summary.retrievedAt)}</strong></div></section>
      </div>
    </div>
  </main>;
}

function OfficialResource({label,detail,href}:{label:string;detail:string;href:string}) { return <a className="resource-row" href={href} target="_blank" rel="noreferrer"><div><strong>{label}</strong><span>{detail}</span></div><ExternalIcon/></a>; }
function PeopleEmpty(){return <div className="people-empty" aria-hidden="true"><PinIcon/></div>}
