"use client";

import { emergencyContacts } from "@/data/emergency-contacts";
import { productionApiCount, productionDataSources, type DataSource } from "@/config/data-sources";
import { AlertIcon, ExternalIcon, PhoneIcon, ShieldIcon } from "@/components/icons";
import { usePreferences } from "@/components/preferences";

const choose = (language: "en" | "ms", en: string, ms: string) => language === "ms" ? ms : en;

export function ContactsContent() {
  const { language } = usePreferences();
  const contactMs: Record<string, { agency: string; purpose: string; coverage: string }> = {
    "nadma-portal": { agency: "Agensi Pengurusan Bencana Negara (NADMA)", purpose: "Maklumat bencana negara rasmi, kemas kini agensi dan pertanyaan umum.", coverage: "Seluruh negara" },
    "jkm-pps": { agency: "Jabatan Kebajikan Masyarakat (JKM)", purpose: "Semakan rasmi Pusat Pemindahan Sementara (PPS) yang aktif dan pertanyaan awam JKM.", coverage: "Seluruh negara" },
  };
  return <main id="main"><section className="inner-hero"><div className="container"><h1>{choose(language,"Emergency contacts","Hubungan kecemasan")}</h1><p>{choose(language,"Verified national emergency and agency contacts in one place.","Hubungan kecemasan negara dan agensi rasmi yang telah disahkan, semuanya di satu tempat.")}</p></div></section><section className="inner-content"><div className="container narrow"><a className="big-call" href="tel:999"><PhoneIcon/><div><span>{choose(language,"Life-threatening emergency","Kecemasan mengancam nyawa")}</span><strong>{choose(language,"Call 999","Hubungi 999")}</strong><p>{choose(language,"Police, Fire and Rescue, ambulance and other emergency services.","Polis, Bomba dan Penyelamat, ambulans serta perkhidmatan kecemasan lain.")}</p></div></a><div className="contact-list">{emergencyContacts.slice(1).map(contact=>{const localized=language === "ms" ? contactMs[contact.id] : undefined;return <article key={contact.id}><div><ShieldIcon/><span>{localized?.coverage ?? contact.coverage}</span></div><h2>{localized?.agency ?? contact.agency}</h2><p>{localized?.purpose ?? contact.purpose}</p>{contact.phone&&<a className="button button-dark" href={`tel:${contact.phone.replace(/[\s-]/g,"")}`}><PhoneIcon/> {choose(language,"Call","Hubungi")} {contact.phone}</a>}{contact.website&&<a className="button button-secondary" href={contact.website} target="_blank" rel="noreferrer">{choose(language,"Open official website","Buka laman web rasmi")} <ExternalIcon/></a>}<small>{choose(language,"Source verified","Sumber disahkan")} {contact.lastVerifiedAt}</small></article>})}</div></div></section></main>;
}

const prepareItems = [
  ["Identification and important documents","Pengenalan diri dan dokumen penting"],
  ["Essential medicine","Ubat-ubatan penting"], ["Drinking water","Air minuman"],
  ["Phone and power bank","Telefon dan bank kuasa"], ["Essential clothing","Pakaian penting"],
  ["Family contact plan","Pelan hubungan keluarga"], ["A familiar meeting point","Tempat pertemuan yang dipersetujui"],
  ["Emergency numbers saved offline","Nombor kecemasan disimpan di luar talian"],
] as const;

export function PrepareContent(){const {language}=usePreferences();return <main id="main"><section className="inner-hero"><div className="container"><span className="eyebrow">{choose(language,"Prepare calmly","Bersedia dengan tenang")}</span><h1>{choose(language,"Prepare my family","Persediaan keluarga saya")}</h1><p>{choose(language,"A lightweight checklist for before flood conditions worsen.","Senarai semak ringkas sebelum keadaan banjir bertambah buruk.")}</p></div></section><section className="inner-content"><div className="container narrow"><div className="guidance-note"><ShieldIcon/><p>{choose(language,"This is general preparedness guidance. Follow current instructions from emergency authorities for your area.","Ini ialah panduan persediaan umum. Ikuti arahan semasa pihak berkuasa kecemasan di kawasan anda.")}</p></div><div className="checklist">{prepareItems.map((item,index)=><label key={item[0]}><input type="checkbox"/><span className="check-number">{String(index+1).padStart(2,"0")}</span><strong>{choose(language,item[0],item[1])}</strong></label>)}</div><div className="offline-note"><strong>{choose(language,"Low-connectivity tip","Petua apabila capaian internet lemah")}</strong><p>{choose(language,"Take a screenshot of this list and save key phone numbers before severe weather. Do not rely on one website during an emergency.","Ambil tangkap layar senarai ini dan simpan nombor telefon penting sebelum cuaca buruk. Jangan bergantung pada satu laman web sahaja semasa kecemasan.")}</p></div></div></section></main>}

const limits = [
  ["TolongNow is an informational mini bounty prototype.","TolongNow ialah prototaip maklumat yang dibangunkan untuk mini bounty."],
  ["It does not dispatch or monitor rescue services.","Ia tidak menghantar atau memantau perkhidmatan penyelamat."],
  ["It does not guarantee that any temporary evacuation centre (PPS) is open or available.","Ia tidak menjamin mana-mana Pusat Pemindahan Sementara (PPS) dibuka atau tersedia."],
  ["It does not verify that a road is passable or provide evacuation routing.","Ia tidak mengesahkan bahawa jalan boleh dilalui atau menyediakan laluan pemindahan."],
  ["It does not generate official warnings or risk scores.","Ia tidak menjana amaran rasmi atau skor risiko."],
  ["Live information may be delayed, stale or temporarily unavailable.","Maklumat langsung mungkin lewat, lapuk atau tidak tersedia buat sementara waktu."],
  ["It does not replace instructions from emergency authorities.","Ia tidak menggantikan arahan pihak berkuasa kecemasan."],
] as const;

export function AboutContent(){const {language}=usePreferences();return <main id="main"><section className="inner-hero"><div className="container"><span className="eyebrow">{choose(language,"Safety first","Utamakan keselamatan")}</span><h1>{choose(language,"What TolongNow can—and cannot—tell you","Perkara yang TolongNow boleh—dan tidak boleh—maklumkan kepada anda")}</h1><p>{choose(language,"Clear boundaries are part of a trustworthy emergency-information product.","Batasan yang jelas ialah sebahagian daripada produk maklumat kecemasan yang boleh dipercayai.")}</p></div></section><section className="inner-content"><div className="container narrow"><div className="danger-panel"><AlertIcon/><div><span>{choose(language,"Immediate danger","Bahaya segera")}</span><h2>{choose(language,"Call 999 now","Hubungi 999 sekarang")}</h2><p>{choose(language,"Do not wait for a website or data feed when life is at risk.","Jangan tunggu laman web atau suapan data apabila nyawa terancam.")}</p></div></div><div className="limitations-list">{limits.map((limit,index)=><div key={limit[0]}><ShieldIcon/><span>{String(index+1).padStart(2,"0")}</span><p>{choose(language,limit[0],limit[1])}</p></div>)}</div></div></section></main>}

const sourceMs: Record<string, Partial<DataSource>> = {
  "met-forecast": { name:"Ramalan cuaca 7 hari MET Malaysia", pasarApiEntryName:"Ramalan cuaca 7 hari (langsung)", provider:"MET Malaysia melalui data.gov.my", usedFor:"Ramalan harian daerah dan julat suhu.", authentication:"Tiada pengesahan diperlukan", revalidation:"30 minit", limitations:"Ramalan daerah bukan pemerhatian pada peringkat jalan dan dibekalkan terutamanya dalam Bahasa Melayu." },
  "met-warning": { name:"Amaran cuaca MET Malaysia", pasarApiEntryName:"Amaran cuaca (langsung)", provider:"MET Malaysia melalui data.gov.my", usedFor:"Teks amaran cuaca rasmi semasa dan tempoh sah.", authentication:"Tiada pengesahan diperlukan", revalidation:"5 minit", limitations:"Amaran mungkin meliputi kawasan yang luas dan dipaparkan menggunakan kata-kata rasmi yang dibekalkan oleh MET Malaysia." },
  nominatim: { name:"Pengekodan geografi Nominatim", provider:"Penyumbang OpenStreetMap", usedFor:"Carian lokasi di Malaysia yang dihantar dan pengekodan geografi songsang bagi koordinat pelayar yang diluluskan pengguna; tiada autolengkap ketika menaip.", authentication:"Tiada pengesahan; User-Agent pengenalan diperlukan", revalidation:"Carian berjaya disimpan dalam cache selama 24 jam", limitations:"Perkhidmatan awam dihadkan kepada satu permintaan sesaat dan hasil bergantung pada liputan OpenStreetMap." },
  "jkm-active-pps": { name:"Pusat pemindahan aktif InfoBencana JKM", pasarApiEntryName:"Integrasi rasmi secara langsung", provider:"Jabatan Kebajikan Masyarakat Malaysia (JKM)", usedFor:"Pusat pemindahan banjir semasa berdekatan pengguna, termasuk koordinat, mangsa, keluarga dan kapasiti.", authentication:"Tiada pengesahan; permintaan sebelah pelayan", revalidation:"5 minit", limitations:"Titik akhir JSON dalaman rasmi tetapi tidak didokumenkan, tanpa SLA, versi skema, CORS atau cap masa respons. TolongNow mengesahkan skema yang ketat dan beralih kepada halaman rasmi JKM apabila sumber tidak tersedia." },
};

export function DataSourcesContent(){const {language}=usePreferences();return <main id="main"><section className="inner-hero data-hero"><div className="container"><span className="eyebrow">{choose(language,"Transparent by design","Ketelusan sejak dari reka bentuk")}</span><h1>{choose(language,"APIs & Data Sources","API & Sumber Data")}</h1><p>{choose(language,`TolongNow uses ${productionApiCount} production data sources. PasarAPI helped discover most integrations; direct official integrations are identified separately.`,`TolongNow menggunakan ${productionApiCount} sumber data produksi. PasarAPI membantu menemukan kebanyakan integrasi; integrasi rasmi secara langsung dikenal pasti secara berasingan.`)}</p><a href="https://pasarapi.xyz/" target="_blank" rel="noreferrer">{choose(language,"Explore PasarAPI","Terokai PasarAPI")} <ExternalIcon/></a></div></section><section className="inner-content"><div className="container"><div className="source-grid">{productionDataSources.map(source=><SourceCard key={source.id} source={language === "ms" ? {...source,...sourceMs[source.id]} : source} language={language}/>)}</div></div></section></main>}

function SourceCard({source,language}:{source:DataSource;language:"en"|"ms"}){const direct=source.pasarApiEntryId==="direct-official";const c=(en:string,ms:string)=>choose(language,en,ms);return <article className="source-card"><div className="source-card-top"><span className="data-type used">{source.dataType === "forecast" ? c("forecast","ramalan") : c("live","langsung")}</span><span className="source-id">{source.pasarApiEntryId}</span></div><h2>{source.name}</h2><dl><div><dt>{direct?c("Integration","Integrasi"):c("Discovered through","Ditemukan melalui")}</dt><dd><a href={source.pasarApiUrl} target="_blank" rel="noreferrer">{direct?source.pasarApiEntryName:`PasarAPI · ${source.pasarApiEntryName}`} <ExternalIcon/></a></dd></div><div><dt>{c("Official provider","Penyedia rasmi")}</dt><dd>{source.provider}</dd></div><div><dt>{c("Used for","Digunakan untuk")}</dt><dd>{source.usedFor}</dd></div><div><dt>{c("Authentication","Pengesahan")}</dt><dd>{source.authentication}</dd></div><div><dt>{c("Cache / refresh","Cache / penyegaran")}</dt><dd>{source.revalidation}</dd></div><div><dt>{c("Endpoint","Titik akhir")}</dt><dd><code>{source.endpoint}</code></dd></div><div><dt>{c("Known limitations","Batasan yang diketahui")}</dt><dd>{source.limitations}</dd></div></dl><a className="official-link" href={source.officialUrl} target="_blank" rel="noreferrer">{c("Official source or documentation","Sumber atau dokumentasi rasmi")} <ExternalIcon/></a></article>}
